### ISSUE TITLE
bule dimacs doesn't seem to work

### ISSUE THREAD

**Issue by jajushubh25** [vale1410/bule#16]
`bule dimacs sample.bul` returns

    c dimacs grounding called.
    prepare with args
    p cnf 10 2
    e 5 8 9 2 3 4 6 7 10 11 0 
    dom[c]. | .
    #exists | [0] |  | all[X] |  | all[Y] |  | dom[Z] | :: | q(X | Y | Z)?.

the sample.bul file contains:

      dom[a].
      dom[b].
      dom[c]. 
      mom[d].
      mom[e].
      dom[X] :: all[X].
      mom[X] :: all[X].
      #exists [0], all[X], all[Y], dom[Z] :: q(X,Y,Z)?
      dom[X], mom[Y] :: dom[Z] : q(X,Y,Z).
      dom[X], dom[Y] :: q(X,Y,c) | q(Y,X,b).

**Comment by jajushubh25** [comment]
tested with latest bule_x64 (3.1.2) present in release.

**Comment by vale1410** [comment]
@jajushubh25  thank you for reporting and improving BULE. 

Should be fixed now. Please test with release 3.1.3. 

https://github.com/vale1410/bule/releases/tag/3.1.3
