### ISSUE TITLE
Flag to remove solver output

### ISSUE THREAD

**Issue by seanskggo72** [vale1410/bule#2]
Hello!

Just wondering if there is an optional flag to suppress the output as shown below. If not, is there any possibility that this can be created soon?

![1](https://user-images.githubusercontent.com/65769889/102751900-cef4e280-43bc-11eb-87a0-9b3a2ecdfa08.PNG)

**Comment by SirZebe** [comment]
I'm assuming you run it through depqbf. Try dropping --qdo flag from your depqbf instance.

(taken from doc's):
*To enable QDIMACS
output generation, run DepQBF with parameter '--qdo'. Note that the
assignment printed by DepQBF can be partial, i.e. not all variables are
necessarily assigned. In this case, the variables for which no value was
printed can be assigned arbitrarily.*

**Comment by seanskggo72** [comment]
Hello!

Sorry for the late response and not clarifying earlier but I am actually using a SAT solver for the problem. I think QBF works now without any output after I got rid of the flag. Is there any way I can disable output for KISSAT? Also where in the docs did you find the information about flags? I'm having trouble finding them...

Bule list:
![2](https://user-images.githubusercontent.com/65769889/102849074-6ebc7a00-446a-11eb-8260-91bc18566fec.PNG)

Using SAT solver:
![3](https://user-images.githubusercontent.com/65769889/102849075-6feda700-446a-11eb-9db2-640a877b47df.PNG)

Output:
![4](https://user-images.githubusercontent.com/65769889/102849077-70863d80-446a-11eb-94c3-fe1dafa4b523.PNG)

**Comment by vale1410** [comment]
Eventually we will include some more elaborate logging of Bule and the solvers beneath. At this point I believe for you the easiest is to grep the lines that you are interested in. For instance if you just want to know if it's SAT or UNSAT then use : 

```
>>> bule solve <instance>  2>/dev/null | grep 's SAT\|s UNSAT'
```

**Comment by seanskggo72** [comment]
Oh ok I see. Will do that :)

Thank you!
