### ISSUE TITLE
Bule2 syntax is not used in the README

### ISSUE THREAD

**Issue by angary** [vale1410/bule#31]
For example `dom[1..3].` should be `#ground dom[1..3]`. Not sure if this is intentional or not. 

Happy to make a PR to update syntax in the [syntax](https://github.com/vale1410/bule#bules-syntax-and-simple-programs) section to bule2 if needed.

**Comment by AbdallahS** [comment]
Yes, this is the syntax of bule1, the readme hasn't been updated alongside the syntax so it is now trailing behind. A PR would be very welcome!
