### ISSUE TITLE
BUG: Comments not properly handled 

### ISSUE THREAD

**Issue by SinghArshdeep** [vale1410/bule#35]
Comments for solvers are improperly handled. 

Modified bule2/lib/Solve.ml to fix the issue:

Below is the code from line 24:
let input_lines inp =
    let l = ref [] in
    (try
       while true do l := input_line inp :: !l done
     with End_of_file -> ());
    List.rev !l
  
  let isnt_comment line = 
    String.length line > 0 && line.[0] <> 'c'

  let run_process cmd dimacs =
    let inp, out = Unix.open_process cmd in
    fprintf out "%s%!" (Dimacs.Print.qbf_file dimacs);
    close_out out;
    let lines = input_lines inp in
    close_in inp;
    let lines = List.filter isnt_comment lines in 
    parse_output lines

**Comment by AbdallahS** [comment]
Thanks, Arshdeep! Would you like to create a pull request with your change? @angary might be able to help you with the process!
